apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: bi4w5o8o7-go-gitops
  description: This is GitOps manifest for bi4w5o8o7-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=bi4w5o8o7-go
    backstage.io/kubernetes-id: bi4w5o8o7-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: bi4w5o8o7-go
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:bi4w5o8o7-go
