apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: bi4w5o8o7-go
  janus-idp.io/tekton: bi4w5o8o7-go
  backstage.io/kubernetes-id: bi4w5o8o7-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: bi4w5o8o7-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
