apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: bi4w5o8o7-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bi4w5o8o7-go 
  name: bi4w5o8o7-go
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: bi4w5o8o7-go
    weight: 100 
